server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**

        - id: mail-service
          uri: http://localhost:8081
          predicates:
            - Path=/mail/**
          filters:
            - StripPrefix=1